/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.trabajopracticon4.vistas;

import com.mycompany.trabajopracticon4.Alumno;
import com.mycompany.trabajopracticon4.Materia;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author martin
 */
public class AgregarMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarMateria
     */
    
    Materia materia;
  
    private HashSet<Materia> materias = new HashSet<>();
    
    public AgregarMateria(HashSet<Materia> materias) {
        initComponents();
        
        this.materias = materias;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JLidMateria = new javax.swing.JLabel();
        JLnombreMateria = new javax.swing.JLabel();
        JLanio = new javax.swing.JLabel();
        JTFIdMateria = new javax.swing.JTextField();
        JTFNombreMateria = new javax.swing.JTextField();
        JTFAnio = new javax.swing.JTextField();
        BTNguardarMateria = new javax.swing.JButton();
        BTNlimpiarMateria = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setResizable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Agregar Materia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 0, 24))); // NOI18N

        JLidMateria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JLidMateria.setText("Id Materia");

        JLnombreMateria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JLnombreMateria.setText("Nombre de la materia");

        JLanio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JLanio.setText("Año");

        JTFIdMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFIdMateriaActionPerformed(evt);
            }
        });

        JTFNombreMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNombreMateriaActionPerformed(evt);
            }
        });

        JTFAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFAnioActionPerformed(evt);
            }
        });

        BTNguardarMateria.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BTNguardarMateria.setText("Guardar");
        BTNguardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNguardarMateriaActionPerformed(evt);
            }
        });

        BTNlimpiarMateria.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BTNlimpiarMateria.setText("Limpiar");
        BTNlimpiarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlimpiarMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(BTNguardarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(BTNlimpiarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLnombreMateria)
                                    .addComponent(JLidMateria)
                                    .addComponent(JLanio))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JTFIdMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(JTFNombreMateria, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTFAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFIdMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLidMateria))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLnombreMateria))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLanio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNguardarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(BTNlimpiarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFIdMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFIdMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFIdMateriaActionPerformed

    private void JTFNombreMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNombreMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNombreMateriaActionPerformed

    private void JTFAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFAnioActionPerformed

    private void BTNguardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNguardarMateriaActionPerformed
        // TODO add your handling code here:

        /* CASOS DE EXCEPCION :
        EL ID MATERIA Y/O AÑO ESTAN VACIO : NumberFormatException
        ------------------
        COMPORTAMIENTO NO ESPERADO :( :

            SE ESTA PERMITIENDO AGREGAR MATERIA CON IDMATERIA Y/O AÑO VALIDO Y NOMBRE DE MATERIA VACIO  <== REVISAR

            */
            try {
                materia = new Materia(Integer.parseInt(JTFIdMateria.getText()), JTFNombreMateria.getText(), Integer.parseInt(JTFAnio.getText()));

                if (materias.contains(materia)) {  // SEGUN PARECE CONTAINS USA EQUIAL Y HASHCODE QUE ESTAN OVERIDE PARA COMPROBAR SI EST CONTENIDO
                    JOptionPane.showMessageDialog(null, "una materia con el mismo ID ya esta registrada");
                } else {

                    if (JTFNombreMateria.getText().equals("")) {

                        JOptionPane.showMessageDialog(null, "No esta permitido dejar campos en blanco");
                    } else {
                        materias.add(materia);
                        JOptionPane.showMessageDialog(null, "Se agrego la materia al sistema");

                  //      JCBinscribirMateria.addItem(materia);

                   //     JCBverMateria.addItem(materia);
                    }

                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "No esta permitido dejar campos en blanco");
            }

    }//GEN-LAST:event_BTNguardarMateriaActionPerformed

    private void BTNlimpiarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlimpiarMateriaActionPerformed
        // TODO add your handling code here:

        JTFIdMateria.setText("");
        JTFNombreMateria.setText("");
        JTFAnio.setText("");
    }//GEN-LAST:event_BTNlimpiarMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNguardarMateria;
    private javax.swing.JButton BTNlimpiarMateria;
    private javax.swing.JLabel JLanio;
    private javax.swing.JLabel JLidMateria;
    private javax.swing.JLabel JLnombreMateria;
    private javax.swing.JTextField JTFAnio;
    private javax.swing.JTextField JTFIdMateria;
    private javax.swing.JTextField JTFNombreMateria;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
