/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.trabajopracticon4.vistas;

import com.mycompany.trabajopracticon4.Alumno;
import com.mycompany.trabajopracticon4.Materia;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author martin
 */
public class Informacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Informacion
     */
    
    private HashSet<Alumno> alumnos = new HashSet<>();
     private HashSet<Materia> materias = new HashSet<>();
    
    public Informacion(HashSet<Alumno> alumnos,HashSet<Materia> materias ) {
        initComponents();
        
        // importar los dos hashset
         this.alumnos = alumnos;
         this.materias = materias;
        CargarComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jElijaUnAlumno2 = new javax.swing.JLabel();
        BTNverMateria = new javax.swing.JButton();
        JCBverMateria = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jElijaUnAlumno1 = new javax.swing.JLabel();
        BTNverAlumno = new javax.swing.JButton();
        JCBverAlumno = new javax.swing.JComboBox<>();

        setClosable(true);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Informacion de materias", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 0, 18))); // NOI18N

        jElijaUnAlumno2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jElijaUnAlumno2.setText("Elija una materia");

        BTNverMateria.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BTNverMateria.setText("ver");
        BTNverMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNverMateriaActionPerformed(evt);
            }
        });

        JCBverMateria.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                JCBverMateriaComponentAdded(evt);
            }
        });
        JCBverMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBverMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jElijaUnAlumno2))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(JCBverMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(BTNverMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jElijaUnAlumno2)
                .addGap(33, 33, 33)
                .addComponent(JCBverMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(BTNverMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Informacion de alumnos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 0, 18))); // NOI18N

        jElijaUnAlumno1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jElijaUnAlumno1.setText("Elija un Alumno");

        BTNverAlumno.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BTNverAlumno.setText("ver");
        BTNverAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNverAlumnoActionPerformed(evt);
            }
        });

        JCBverAlumno.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                JCBverAlumnoComponentAdded(evt);
            }
        });
        JCBverAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBverAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jElijaUnAlumno1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBverAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BTNverAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jElijaUnAlumno1)
                .addGap(36, 36, 36)
                .addComponent(JCBverAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNverAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNverMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNverMateriaActionPerformed
        // TODO add your handling code here:

        try {
            JOptionPane.showMessageDialog(null, "Nombre  :  " + ((Materia)JCBverMateria.getSelectedItem()).getNombre()+
                "\nID  : "    + ((Materia)JCBverMateria.getSelectedItem()).getIdMateria()+
                "\nAño : "    + ((Materia)JCBverMateria.getSelectedItem()).getAnio());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "verifique de seleccionar una materia");

        }

    }//GEN-LAST:event_BTNverMateriaActionPerformed

    private void JCBverMateriaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_JCBverMateriaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBverMateriaComponentAdded

    private void JCBverMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBverMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBverMateriaActionPerformed

    private void BTNverAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNverAlumnoActionPerformed
        // TODO add your handling code here:

        try {

            JOptionPane.showMessageDialog(null, "Apellido y nombre : " + ((Alumno)JCBverAlumno.getSelectedItem()).toString()
                + "\nNumero de legajo : " + ((Alumno)JCBverAlumno.getSelectedItem()).getLegajo()
                + "\nCantidad de materias a las que esta inscripto : " + ((Alumno)JCBverAlumno.getSelectedItem()).cantidadMaterias()
                + "\nMaterias a la/s que esta inscripta/o : \n" + ((Alumno)JCBverAlumno.getSelectedItem()).getMateria());

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "verifique de seleccionar un alumno");

        }

    }//GEN-LAST:event_BTNverAlumnoActionPerformed

    private void JCBverAlumnoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_JCBverAlumnoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBverAlumnoComponentAdded

    private void JCBverAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBverAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBverAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNverAlumno;
    private javax.swing.JButton BTNverMateria;
    private javax.swing.JComboBox<Alumno> JCBverAlumno;
    private javax.swing.JComboBox<Materia> JCBverMateria;
    private javax.swing.JLabel jElijaUnAlumno1;
    private javax.swing.JLabel jElijaUnAlumno2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables

    private void CargarComboBox() {
        
        for (Alumno alumno : alumnos) {
         
              JCBverAlumno.addItem(alumno);
            
        }
                
        for (Materia materia : materias) {
         
              JCBverMateria.addItem(materia);
            
        }
        
    }
}
