/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.trabajopracticon4.vistas;

import com.mycompany.trabajopracticon4.Alumno;
import com.mycompany.trabajopracticon4.Materia;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author martin
 */
public class InscripcionAMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form InscripcionAMateria
     */
     private HashSet<Alumno> alumnos = new HashSet<>();
     private HashSet<Materia> materias = new HashSet<>();
    
    public InscripcionAMateria(HashSet<Alumno> alumnos,HashSet<Materia> materias ) {
        initComponents();
        
        // importar los dos hashset
         this.alumnos = alumnos;
         this.materias = materias;
        CargarComboBox();
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jElijaunaMateria = new javax.swing.JLabel();
        jElijaUnAlumno = new javax.swing.JLabel();
        BTNInscribir = new javax.swing.JButton();
        JCBinscribirMateria = new javax.swing.JComboBox<>();
        JCBinscribirAlumno = new javax.swing.JComboBox<>();

        setClosable(true);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Inscripcion a materias", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 0, 18))); // NOI18N

        jElijaunaMateria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jElijaunaMateria.setText("Elija una Materia");

        jElijaUnAlumno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jElijaUnAlumno.setText("Elija un Alumno");

        BTNInscribir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BTNInscribir.setText("Inscribir");
        BTNInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInscribirActionPerformed(evt);
            }
        });

        JCBinscribirMateria.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                JCBinscribirMateriaComponentAdded(evt);
            }
        });
        JCBinscribirMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBinscribirMateriaActionPerformed(evt);
            }
        });

        JCBinscribirAlumno.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                JCBinscribirAlumnoComponentAdded(evt);
            }
        });
        JCBinscribirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBinscribirAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jElijaUnAlumno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JCBinscribirAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jElijaunaMateria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JCBinscribirMateria, 0, 140, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(BTNInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jElijaunaMateria)
                    .addComponent(JCBinscribirMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jElijaUnAlumno)
                    .addComponent(JCBinscribirAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(BTNInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInscribirActionPerformed
        // TODO add your handling code here:

        //  JTFELijaUnaMateria.getSelectedItem();  no se que hace
        //  System.out.println(JTFELijaUnaMateria.getItemAt(0)); muetra el objeto de un indice particular
        //   System.out.println(JTFELijaUnaMateria.getSelectedIndex());  indice del elemento seleccionado dentro del JComboBox
        /* CASOS DE EXCEPCION :
        COMBOBOX MATERIA VACIO Y COMBOBOX ALUMNO NO VACIO : NullPointerException
        COMBOBOX MATERIA VACIO Y COMBOBOX ALUMNO VACIO : NullPointerException
        COMBOBOX MATERIA NO VACIO Y COMBOBOX ALUMNO VACIO : NullPointerException
        EN DEFINITIVA SI ALGUN COMBOBOX DE INSCRIPCION ESTA VACIO
        ------------------
        COMPORTAMIENTO NO ESPERADO :( :

            SE ESTA PERMITIENDO AGREGAR ALUMNOS CON LEGAJO VALIDO PERO CON NOMBRE Y APELLIDO VACION <== REVISAR

            */
         //   ((Alumno)JCBinscribirAlumno.getSelectedItem())
        
            try {
                if (((Alumno)JCBinscribirAlumno.getSelectedItem()).getMateria().contains((Materia)JCBinscribirMateria.getSelectedItem())) {

                    JOptionPane.showMessageDialog(null, "Este alumno ya esta registrado en esa materia");
                } else {

                    if (((Materia)JCBinscribirMateria.getSelectedItem()) == null) {
                        JOptionPane.showMessageDialog(null, "Verifique de seleccionar una materia \nNo esta permitido dejar campos en blanco");
                    } else {
                        ((Alumno)JCBinscribirAlumno.getSelectedItem()).agregarMateria((Materia)JCBinscribirMateria.getSelectedItem());

                        JOptionPane.showMessageDialog(null,((Alumno)JCBinscribirAlumno.getSelectedItem()).toString()
                            + "  Se a inscripto con exito a la materia  : "
                            + ((Alumno)JCBinscribirAlumno.getSelectedItem()));

                        // JTFElijaUnAlumno.getItemAt(JTFElijaUnAlumno.getSelectedIndex()).getMateria());
                }

            }

        } catch (NullPointerException e) {

            JOptionPane.showMessageDialog(null, "Verifique de seleccionar un alumno \nNo esta permitido dejar campos en blanco");
        }

        // System.out.println(JTFElijaUnAlumno.getItemAt(JTFElijaUnAlumno.getSelectedIndex()));
    }//GEN-LAST:event_BTNInscribirActionPerformed

     private void CargarComboBox() {
        
        for (Alumno alumno : alumnos) {
         
              JCBinscribirAlumno.addItem(alumno);
            
        }
                
        for (Materia materia : materias) {
         
              JCBinscribirMateria.addItem(materia);
            
        }
        
    }
    
    private void JCBinscribirMateriaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_JCBinscribirMateriaComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_JCBinscribirMateriaComponentAdded

    private void JCBinscribirMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBinscribirMateriaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JCBinscribirMateriaActionPerformed

    private void JCBinscribirAlumnoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_JCBinscribirAlumnoComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_JCBinscribirAlumnoComponentAdded

    private void JCBinscribirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBinscribirAlumnoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JCBinscribirAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNInscribir;
    private javax.swing.JComboBox<Alumno> JCBinscribirAlumno;
    private javax.swing.JComboBox<Materia> JCBinscribirMateria;
    private javax.swing.JLabel jElijaUnAlumno;
    private javax.swing.JLabel jElijaunaMateria;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
